# Site settings
title: Movement Creates Connection
email: gregdyke@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts about music and dance in the intersection of Bal Folk, Blues,
  Lindy Hop and Tango.  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gregdyke.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
